### ISSUE TITLE
Unable to use action login with GitHub Actions Beta

### ISSUE THREAD

**Issue by Yvand** [actions/docker#28]
Hello, I'm using the new GitHub Actions Beta and Docker cli actions work fine (at least "build" and "tag"), but I'm unable to use the login action. Here is my sample: 

```yaml
- name: Sign-in to Docker
      uses: actions/docker/login@master
      with:
        secrets: ["${{ secrets.GITHUB_DOCKER_USERNAME }}", "${{ secrets.GITHUB_DOCKER_PASSWORD }}"]
```

I get this error message:
```
Your workflow file was invalid: .github/workflows/BuildDev.yml (Line: 62, Col: 18): A sequence was not expected
```

Line 62 is the one starting with "secrets:"
Of course in the repo I defined secrets "GITHUB_DOCKER_USERNAME" and "GITHUB_DOCKER_PASSWORD".
Any idea what I'm doing wrong?
