### ISSUE TITLE
Docker exec bash running

### ISSUE THREAD

**Issue by aslan9** [actions/docker#29]
From my current observation, Github Action does not support us to easily run commands within a determined docker container (in dockerhub)?

We are using circleci, and setup our docker image as an executor. Is there any way in Action framework to use container like executor? Right now, the only way I can come up with is to create a Dockerfile Action and put all commands into entrypoints.

**Comment by mramsden** [comment]
I was playing around with this myself recently and I managed to come up with the following:

```
test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: actions/docker/cli@master
      with:
        args: build -t mramsden/raidcalendar .
    - name: Test
      uses: actions/docker/cli@master
      with:
        args: "container run mramsden/raidcalendar /bin/sh -c 'npm install && npm test'"
```

The custom script execution happens in the Test step of that part of the workflow. That means that I can build the container first then execute my tests inside that container before I continue to other parts of the script process.
