### ISSUE TITLE
docker login does not seem to work with new github actions

### ISSUE THREAD

**Issue by steebchen** [actions/docker#30]
I just migrated to the new GitHub Actions v2, but I get this error:

```
Error: Cannot perform an interactive login from a non TTY device
```

![Selection_871](https://user-images.githubusercontent.com/5013932/64478153-48ef6100-d1a4-11e9-8ba5-731f286b8b40.jpg)

My secrets:

![Selection_873](https://user-images.githubusercontent.com/5013932/64478151-45f47080-d1a4-11e9-999a-ba1588899a6e.jpg)

relevant config snippet:

```
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: steebchen
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
```

I also tried manually setting the command with `args`, but it resulted in the same error.
