### ISSUE TITLE
Permission denied to create file in "/github/home/" folder

### ISSUE THREAD

**Issue by epomatti** [actions/docker#31]
I have this simple workflow to build a Flutter app, but it is failing to create a file at the home `/github/home/`folder.

```
Run flutter pub get

FileSystemException: Cannot create file, path = '/github/home/.flutter' (OS Error: Permission denied, errno = 13)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.createSync (dart:io/file_impl.dart:281:5)
```

I attached the container initialization log and it is possible to see that the docker image has the home volume mapped to it.

```
name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter:v1.7.8-hotfix.4
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: flutter pub get
      working-directory: snake_tracker_app
    - name: Run tests
      run: flutter test
      working-directory: snake_tracker_app
```

[initialize-containers.log](https://github.com/actions/docker/files/3587247/initialize-containers.log)
[install-dependencies.log](https://github.com/actions/docker/files/3587248/install-dependencies.log)
