### ISSUE TITLE
Docker login succeed and then no basic auth credentials

### ISSUE THREAD

**Issue by drodriguezhdez** [actions/docker#32]
On my workflow, I'm using `docker login` action like following:

```
- uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{secrets.docker_username}}
          DOCKER_PASSWORD: ${{secrets.docker_password}}
```
obtaining `Login Succeeded`.

But, other GitHub action try to pull some image, and I'm obtaining:
```
Get https://docker.pkg.github.com/v2/undefinedlabs/maven-jdk18-perl-alpine/maven-jdk18-perl-alpine/manifests/0.1.0: no basic auth credentials
##[error]Docker build failed with exit code 1
```

Did I miss something?
